[package]
name = "sisyphus32"
version = "0.1.0"
edition = "2021"
default-run = "sisyphus32"

[dependencies]
rand = "0.9.0"
rayon = "1.10.0"
ctor = "0.3.6"

[profile.release-with-debug]
inherits = "release"
debug = true

[profile.release-all]
inherits = "release"

[features]

# Playable versions:
random = ["default_base"]
minimax = ["default_base", "search_minimax"]
negamax = ["default_base", "search_negamax"]
piece_positions = ["negamax", "eval_piece_positions"]
sorted = ["piece_positions", "move_sort"]
quiescence_eval = ["sorted", "quiescence"]
quiescence_en_passant = ["quiescence_eval", "en_passant_in_quiescence"]
checks_increment_depth = ["quiescence_en_passant", "checks_add_depth"]
killers = ["checks_increment_depth", "killer_moves"]
butterfly = ["killers", "butterfly_heuristic"]
tt = ["butterfly", "transposition_table"]
eval_tt = ["tt", "eval_transposition_table"]
tttt = ["eval_tt", "tt_two_tier"]
default = ["tttt"] # Should only be one feature from the list of playable versions

# Base features (should not be set as default feature):
basic =                 ["board_representation_bitboard", "perft_single_thread", "revert_with_undo_move", "sliders_on_the_fly"]
magic_bitboard =        ["board_representation_bitboard", "perft_single_thread", "revert_with_undo_move", "sliders_magic_bitboards"]
single_thread_bb =      ["board_representation_bitboard", "perft_single_thread", "revert_with_clone", "sliders_magic_bitboards"]
parallel_bb =           ["board_representation_bitboard", "perft_parallelize", "revert_with_clone", "sliders_magic_bitboards"]
single_thread_array =   ["board_representation_array", "perft_single_thread", "revert_with_clone", "sliders_magic_bitboards"]
parallel_array =        ["board_representation_array", "perft_parallelize", "revert_with_clone", "sliders_magic_bitboards"]
default_base =          ["parallel_array"] # The feature used for all playable versions

# Individual features (should not be set as default feature):
board_representation_bitboard = []
board_representation_array = []

perft_parallelize = []
perft_single_thread = []

revert_with_clone = []
revert_with_undo_move = []

sliders_magic_bitboards = []
sliders_on_the_fly = []

search_minimax = []
search_negamax = []

eval_piece_positions = []

iterative_deepening = []

quiescence = []

move_sort = []

en_passant_in_quiescence = []

transposition_table = []

small_transposition_table = []

eval_transposition_table = []

tt_two_tier = []

killer_moves = []

butterfly_heuristic = []

checks_add_depth = []
