[package]
name = "sisyphus32"
version = "0.1.0"
edition = "2021"
default-run = "sisyphus32"

[dependencies]
rand = "0.9.0"
rayon = "1.10.0"
ctor = "0.3.6"

[profile.release-with-debug]
inherits = "release"
debug = true

[features]
default = ["array_copy_tt_killer_butterfly"]

basic =                 ["board_representation_bitboard", "perft_single_thread", "revert_with_undo_move", "sliders_on_the_fly", "search_random", "eval_piece_positions"]
magic_bitboard =        ["board_representation_bitboard", "perft_single_thread", "revert_with_undo_move", "sliders_magic_bitboards", "search_random", "eval_piece_positions"]
single_thread_bb =      ["board_representation_bitboard", "perft_single_thread", "revert_with_clone", "sliders_magic_bitboards", "search_negamax", "eval_piece_positions"]
parallel_bb =           ["board_representation_bitboard", "perft_parallelize", "revert_with_clone", "sliders_magic_bitboards", "search_negamax", "eval_piece_positions"]
single_thread_array =   ["board_representation_array", "perft_single_thread", "revert_with_clone", "sliders_magic_bitboards", "search_negamax", "eval_piece_positions"]
parallel_array =        ["board_representation_array", "perft_parallelize", "revert_with_clone", "sliders_magic_bitboards", "search_negamax", "eval_piece_positions"]

array_copy = ["parallel_array", "iterative_deepening", "move_sort", "quiescence", "en_passant_in_quiescence", "checks_add_depth"]
array_copy_tt = ["array_copy", "transposition_table", "eval_transposition_table", "tt_two_tier"]
array_copy_tt_killer = ["array_copy_tt", "killer_moves"]
array_copy_tt_butterfly = ["array_copy_tt", "butterfly_heuristic"]
array_copy_tt_killer_butterfly = ["array_copy_tt", "killer_moves", "butterfly_heuristic"]

board_representation_bitboard = []
board_representation_array = []

perft_parallelize = []
perft_single_thread = []

revert_with_clone = []
revert_with_undo_move = []

sliders_magic_bitboards = []
sliders_on_the_fly = []

search_minimax = []
search_random = []
search_negamax = []

eval_basic = []
eval_piece_positions = []

iterative_deepening = []

quiescence = []

move_sort = []

en_passant_in_quiescence = []

transposition_table = []

small_transposition_table = []

eval_transposition_table = []

tt_always_replace = []
tt_two_tier = [] # tttt hehe

killer_moves = []

butterfly_heuristic = []

checks_add_depth = []
