[package]
name = "Sisyphus32"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.9.0"
rayon = "1.10.0"

[features]
default = ["single_thread_array"]

basic =                 ["board_representation_bitboard", "perft_single_thread", "revert_with_undo_move", "sliders_on_the_fly", "search_random", "iterative_deepening"]
magic_bitboard =        ["board_representation_bitboard", "perft_single_thread", "revert_with_undo_move", "sliders_magic_bitboards", "search_random", "iterative_deepening"]
single_thread_bb =      ["board_representation_bitboard", "perft_single_thread", "revert_with_clone", "sliders_magic_bitboards", "search_minimax", "iterative_deepening"]
parallel_bb =           ["board_representation_bitboard", "perft_parallelize", "revert_with_clone", "sliders_magic_bitboards", "search_minimax", "iterative_deepening"]
single_thread_array =   ["board_representation_array", "perft_single_thread", "revert_with_clone", "sliders_magic_bitboards", "search_minimax", "iterative_deepening"]
parallel_array =        ["board_representation_array", "perft_parallelize", "revert_with_clone", "sliders_magic_bitboards", "search_minimax", "iterative_deepening"]

board_representation_bitboard = []
board_representation_array = []

perft_parallelize = []
perft_single_thread = []

revert_with_clone = []
revert_with_undo_move = []

sliders_magic_bitboards = []
sliders_on_the_fly = []

search_minimax = []
search_random = []

iterative_deepening = []
no_iterative_deepening = []
