name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run Tests
      run: |
        cargo test --release --no-default-features --features "basic, small_transposition_table"
        cargo test --release --no-default-features --features "magic_bitboard, small_transposition_table"
        cargo test --release --no-default-features --features "single_thread_bb, small_transposition_table"
        cargo test --release --no-default-features --features "parallel_bb, small_transposition_table"
        cargo test --release --no-default-features --features "single_thread_array, small_transposition_table"
        cargo test --release --no-default-features --features "parallel_array, small_transposition_table"
        cargo test --release --no-default-features --features "array_copy_tt, small_transposition_table"
