name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run Tests
      run: |
        cargo test --verbose --release --no-default-features --features basic
        cargo test --verbose --release --no-default-features --features magic_bitboard
        cargo test --verbose --release --no-default-features --features single_thread_bb
        cargo test --verbose --release --no-default-features --features parallel_bb
        cargo test --verbose --release --no-default-features --features single_thread_array
        cargo test --verbose --release --no-default-features --features parallel_array
